<?php

declare(strict_types=1);

namespace App\Aggregates\SharePooling\Repositories;

use Domain\Aggregates\SharePooling\Repositories\SharePoolingMessageRepository as SharePoolingMessageRepositoryInterface;
use EventSauce\MessageRepository\IlluminateMessageRepository\IlluminateUuidV4MessageRepository;

class SharePoolingMessageRepository extends IlluminateUuidV4MessageRepository implements SharePoolingMessageRepositoryInterface
{
}
