name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PHP_VERSION: "8.2"
  PHP_EXTENSIONS: "bcmath"

jobs:

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Check coding style
        run: vendor/bin/pint --test

  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Analyse code
        run: vendor/bin/phpstan

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
        dependency-versions:
          - "lowest"
          - "highest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: xdebug

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Run test suite
        run: vendor/bin/pest --coverage --min=100
