name: Release

on:
  push:
    tags: ["*"]

env:
  APP_ENV: "local"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: "bcmath"
          coverage: "none"

      - name: Validate dependencies
        run: "composer validate --strict"

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Build archive
        run: "php dime app:build dime --build-version=${{ github.ref_name }}"

      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ./builds/dime
          generate_release_notes: true

      - name: Update README
        run: "php release.php ${{ github.ref_name }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "Updated README"